server:
  port: 80
---
spring:
  profiles: local
server:
  port: 80
---
spring:
  profiles: dev
server:
  port: 80
---
spring:
  profiles: real
server:
  port: 80
---

property:
  test:
    name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green
